x-common: &common
  restart: always
  env_file:
    - .env

x-common-volumes: &common-volumes
  volumes:
    - ./app:/app/app
    - ./alembic:/app/alembic
    - ./requirements.txt:/app/requirements.txt
    - ./.env:/app/.env
    - ./app/data:/app/app/data


services:
  db:
    image: postgres:17
    <<: *common
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aic_db
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./mount-data/db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5555:5432
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  # alembic:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   <<: [*common, *common-volumes]
  #   command: [ "alembic", "upgrade", "head" ]
  #   restart: "no"
  #   depends_on:
  #     db:
  #       condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    <<: [*common, *common-volumes]
    ports:
      - 8000:8000
    command: ["sh", "-c", "pip install -r requirements-local.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    depends_on:
      db:
        condition: service_healthy
      # alembic:
      #   condition: service_completed_successfully