"""add role to judges

Revision ID: add_role_to_judges
Revises: rename_status
Create Date: 2024-03-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_role_to_judges'
down_revision = 'rename_status'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judges', sa.Column('role', sa.String(50), nullable=True))
    
    # Set default role to 'judge' for existing records
    op.execute("UPDATE judges SET role = 'judge' WHERE role IS NULL")
    
    # Make role not nullable after setting default values
    op.alter_column('judges', 'role',
               existing_type=sa.String(50),
               nullable=False)
    
    # Add index on role column
    op.create_index(op.f('ix_judges_role'), 'judges', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_judges_role'), table_name='judges')
    op.drop_column('judges', 'role')
    # ### end Alembic commands ###
