"""Add project_title, description, technology to submissions

Revision ID: add_submission_fields
Revises: initial_
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_submission_fields'
down_revision = 'initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('project_title', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('description', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('technology', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'technology')
    op.drop_column('submissions', 'description')
    op.drop_column('submissions', 'project_title')
    # ### end Alembic commands ###
