"""Remove round_submission from submissions

Revision ID: remove_round_submission
Revises: add_submission_fields
Create Date: 2024-05-25 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'remove_round_submission'
down_revision = 'add_submission_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.engine.reflection import Inspector
    from alembic import op
    
    # Kiểm tra xem cột có tồn tại không trước khi xóa
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('submissions')]
    
    if 'round_submission' in columns:
        op.drop_column('submissions', 'round_submission')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('round_submission', sa.String(), nullable=True))
    # ### end Alembic commands ###
