"""Rename status to status_submission

Revision ID: rename_status_to_status_submission
Revises: remove_round_submission
Create Date: 2024-05-26 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'rename_status'
down_revision = 'remove_round_submission'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename column using PostgreSQL syntax
    op.execute('ALTER TABLE submissions RENAME COLUMN status TO status_submission')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename column back using PostgreSQL syntax
    op.execute('ALTER TABLE submissions RENAME COLUMN status_submission TO status')
    # ### end Alembic commands ###
